name: routine
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.7.1
  lint: ^1.1.1
  dartz: ^0.8.9
  equatable: ^1.1.1
  path_provider: ^1.6.7
  injectable: ^0.3.0
  get_it: ^4.0.2
  json_annotation: ^3.0.1
  sembast: ^2.4.3
  auto_route: ^0.4.5
  mobx: ^1.1.1
  flutter_mobx: ^1.1.0
  intl: ^0.16.1
  timetable: ^0.1.1
  time_machine: ^0.9.12

  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.9.0
  freezed: ^0.10.7
  mockito: ^4.1.1
  injectable_generator: ^0.3.4
  json_serializable: ^3.3.0
  auto_route_generator: ^0.4.8
  mobx_codegen: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - packages/time_machine/data/cultures/cultures.bin
    - packages/time_machine/data/tzdb/tzdb.bin
